In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/iris-dataset/iris.csv


# > ***Evaluation of MLP [Multi-layer Perceptron] Classifier Performance on Iris Dataset***

In [2]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics.cluster import adjusted_rand_score
from sklearn.metrics import confusion_matrix 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
iris = load_iris()
#print(iris)

In [4]:
X, y = iris.data, iris.target

X_train, test_x, y_train, test_lab = train_test_split(X, y, test_size = 0.3, random_state = 42)
print(X_train.shape, test_x.shape, len(y_train), len(test_lab))

(105, 4) (45, 4) 105 45


In [5]:
clf = MLPClassifier(solver="lbfgs", alpha=1e-5, hidden_layer_sizes=(15, ), random_state=1)
clf.fit(X_train, y_train)


MLPClassifier(alpha=1e-05, hidden_layer_sizes=(15,), random_state=1,
              solver='lbfgs')

In [6]:
y_pred = clf.predict(test_x)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0]


In [7]:
print("Original", test_lab, len(test_lab))

Original [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0] 45


In [8]:
y_pred = np.asarray(y_pred)
y_true = np.asarray(test_lab)

print(confusion_matrix(y_pred, y_true))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [9]:
# Compute confusion matrix
cm = confusion_matrix(test_lab, y_pred)

# Extract TP, TN, FP, FN values
TP = cm[1, 1]  # True Positive
TN = cm[0, 0]  # True Negative
FP = cm[0, 1]  # False Positive
FN = cm[1, 0]  # False Negative

print(f'for class 2: True Positive = {TP} True Negative = {TN} False Positive = {FP} False Negative = {FN}')

for class 2: True Positive = 13 True Negative = 19 False Positive = 0 False Negative = 0


In [10]:
TPR = TP/(TP+FN)
FPR = FP/(FP+TN)
Prec = TP/(TP+FP)
Rec = TP/(TP+FN)

print(f'True Positive Rate: {TPR}, False Positive Rate: {FPR}, Precision Value: {Prec}, Recall Value: {Rec}')

True Positive Rate: 1.0, False Positive Rate: 0.0, Precision Value: 1.0, Recall Value: 1.0
